# Appending demographic information to dataset using ZIP codes

In [45]:
from uszipcode import SearchEngine, SimpleZipcode, ComprehensiveZipcode
import pandas as pd

In [25]:
df = pd.read_csv(r"C:\Users\email\OneDrive\Documents\Python\zip_codes\cluster_data_pregrouping.csv")
df.head(10)

,ProviderID,CCN,Type_Of_Facility,Medicare_Certified_Beds,Total_Staffed_Beds,ZipCode,KeepState,FINAL_Zip_First_3,FINAL_RUCA1,Hospital_Overall_rating,Per_Patient_spend_State,Per_Patient_spend_Facility,FINAL_Total_Staffed_Beds,FINAL_Total_Medicare_Certified_Beds,FINAL_Medicare_Spend_Per_Patient
0,706051,53300,Childrens,358.0,358.0,93720,CA,937,1,NaN,1.00,Not Available,358.0,358.0,1.00
1,706051,53300,Childrens,358.0,358.0,93230,CA,932,1,NaN,1.00,Not Available,358.0,358.0,1.00
2,2537483,60076,Short Term Acute Care,36.0,25.0,80751,CO,807,4,NaN,1.01,0.95,25.0,36.0,0.95
3,705834,100075,Short Term Acute Care,1364.0,1218.0,33607,FL,336,1,4,1.01,1.00,1218.0,1364.0,1.00
4,705834,100075,Short Term Acute Care,1364.0,1218.0,33614,FL,336,1,4,1.01,1.00,1218.0,1364.0,1.00
5,703752,100265,Short Term Acute Care,300.0,299.0,34695,FL,346,1,5,1.01,1.03,299.0,300.0,1.03
6,703415,10001,Short Term Acute Care,420.0,332.0,36301,AL,363,1,NaN,0.99,1.09,332.0,420.0,1.09
7,2537056,10005,Short Term Acute Care,240.0,195.0,35957,AL,359,4,NaN,0.99,0.88,195.0,240.0,0.88
8,2537057,10006,Short Term Acute Care,338.0,223.0,35630,AL,356,1,NaN,0.99,1.07,223.0,338.0,1.07
9,702904,10007,Short Term Acute Care,99.0,59.0,36467,AL,364,7,NaN,0.99,Not Available,59.0,99.0,0.99

In [124]:
print(df.shape)

(27540, 15)

In [73]:
se = SearchEngine()
zip_df = []
for i in df["ZipCode"].dropna().unique():
    row = [i]
    x = se.by_zipcode(i)
    row.append(x.lat)
    row.append(x.lng)
    row.append(x.bounds_north)
    row.append(x.bounds_south)
    row.append(x.bounds_east)
    row.append(x.bounds_west)
    row.append(x.radius_in_miles)
    row.append(x.land_area_in_sqmi)
    row.append(x.water_area_in_sqmi)

    row.append(x.population)
    row.append(x.population_density)

    row.append(x.housing_units)
    row.append(x.occupied_housing_units)
    row.append(x.median_home_value)
    row.append(x.median_household_income)
    zip_df.append(row)

zipped = pd.DataFrame(zip_df, columns=["ZipCode", "Latitude", "Longitude", "BoundNorth", "BoundSouth", "BoundEast", "BoundWest", "RadiusInMiles", "LandArea", "WaterArea", "Population", "PopulationDensity", "HousingUnits", "OccupiedHousingUnits", "MedianHomeValue", "MedianHouseholdIncome" ])
zipped.head(10)

,ZipCode,Latitude,Longitude,BoundNorth,BoundSouth,BoundEast,BoundWest,RadiusInMiles,LandArea,WaterArea,Population,PopulationDensity,HousingUnits,OccupiedHousingUnits,MedianHomeValue,MedianHouseholdIncome
0,93720,36.86,-119.76,36.893671,36.836113,-119.729551,-119.792790,3.0,9.96,0.05,45191.0,4538.0,18236.0,17368.0,266300.0,75200.0
1,93230,36.27,-119.63,36.443110,36.108339,-119.474354,-119.774504,15.0,261.81,0.95,65264.0,249.0,22331.0,21067.0,182500.0,52611.0
2,80751,40.62,-103.19,40.833163,40.436087,-102.942211,-103.518795,20.0,469.75,4.21,18857.0,40.0,7113.0,6466.0,120700.0,38946.0
3,33607,27.96,-82.49,27.996218,27.950359,-82.464181,-82.575690,5.0,9.03,0.56,23541.0,2607.0,11159.0,9552.0,113500.0,31831.0
4,33614,28.00,-82.51,28.037313,27.966366,-82.484200,-82.527625,3.0,9.78,0.39,46449.0,4751.0,20488.0,18346.0,114600.0,35098.0
5,34695,28.00,-82.69,28.048992,27.977836,-82.661692,-82.709235,3.0,5.31,3.32,17496.0,3297.0,8413.0,7630.0,209000.0,58750.0
6,36301,31.14,-85.40,31.231326,31.069331,-85.309538,-85.507453,7.0,89.27,0.64,35759.0,401.0,15896.0,14494.0,106300.0,37708.0
7,35957,34.20,-86.15,34.284598,34.099073,-85.999490,-86.386168,14.0,79.58,0.25,15693.0,197.0,6535.0,5974.0,98800.0,37546.0
8,35630,34.82,-87.66,34.883895,34.774163,-87.602530,-87.730358,4.0,25.10,4.14,32629.0,1300.0,16672.0,14705.0,98000.0,31100.0
9,36467,31.29,-86.25,31.455716,31.131453,-86.137571,-86.381343,14.0,165.55,1.69,10058.0,61.0,4778.0,4139.0,80300.0,36029.0

In [123]:
# zipped.to_csv('zipped.csv')
print(len(zipped["ZipCode"]))
print(len(zipped["ZipCode"].unique()))

10236
10236

In [109]:
output = pd.merge(left = df, right = zipped, how =  'left', on = 'ZipCode')
new_output = []
for i in output["CCN"]:
    i = str(i)
    while(len(i) < 6):
        i = "0" + i
    new_output.append(i)
output['CCN'] = new_output
output.head(10)

,ProviderID,CCN,Type_Of_Facility,Medicare_Certified_Beds,Total_Staffed_Beds,ZipCode,KeepState,FINAL_Zip_First_3,FINAL_RUCA1,Hospital_Overall_rating,...,BoundWest,RadiusInMiles,LandArea,WaterArea,Population,PopulationDensity,HousingUnits,OccupiedHousingUnits,MedianHomeValue,MedianHouseholdIncome
0,706051,053300,Childrens,358.0,358.0,93720,CA,937,1,NaN,...,-119.792790,3.0,9.96,0.05,45191.0,4538.0,18236.0,17368.0,266300.0,75200.0
1,706051,053300,Childrens,358.0,358.0,93230,CA,932,1,NaN,...,-119.774504,15.0,261.81,0.95,65264.0,249.0,22331.0,21067.0,182500.0,52611.0
2,2537483,060076,Short Term Acute Care,36.0,25.0,80751,CO,807,4,NaN,...,-103.518795,20.0,469.75,4.21,18857.0,40.0,7113.0,6466.0,120700.0,38946.0
3,705834,100075,Short Term Acute Care,1364.0,1218.0,33607,FL,336,1,4,...,-82.575690,5.0,9.03,0.56,23541.0,2607.0,11159.0,9552.0,113500.0,31831.0
4,705834,100075,Short Term Acute Care,1364.0,1218.0,33614,FL,336,1,4,...,-82.527625,3.0,9.78,0.39,46449.0,4751.0,20488.0,18346.0,114600.0,35098.0
5,703752,100265,Short Term Acute Care,300.0,299.0,34695,FL,346,1,5,...,-82.709235,3.0,5.31,3.32,17496.0,3297.0,8413.0,7630.0,209000.0,58750.0
6,703415,010001,Short Term Acute Care,420.0,332.0,36301,AL,363,1,NaN,...,-85.507453,7.0,89.27,0.64,35759.0,401.0,15896.0,14494.0,106300.0,37708.0
7,2537056,010005,Short Term Acute Care,240.0,195.0,35957,AL,359,4,NaN,...,-86.386168,14.0,79.58,0.25,15693.0,197.0,6535.0,5974.0,98800.0,37546.0
8,2537057,010006,Short Term Acute Care,338.0,223.0,35630,AL,356,1,NaN,...,-87.730358,4.0,25.10,4.14,32629.0,1300.0,16672.0,14705.0,98000.0,31100.0
9,702904,010007,Short Term Acute Care,99.0,59.0,36467,AL,364,7,NaN,...,-86.381343,14.0,165.55,1.69,10058.0,61.0,4778.0,4139.0,80300.0,36029.0

In [115]:
output.to_csv("output.csv")
output.shape

(27540, 30)

In [141]:
provider_directory_1 = pd.read_csv(r"C:\Users\email\OneDrive\Documents\Python\zip_codes\CMS_provider_directory_all.csv")
provider_directory_2 = pd.read_csv(r"C:\Users\email\OneDrive\Documents\Python\zip_codes\CMS_directory_every_provider.csv")
provider_directory = provider_directory_1.append(other = provider_directory_2).drop(columns = ['Unnamed: 0'])
provider_directory = provider_directory.rename({'ProviderID' : 'CCN'}, axis = 'columns').drop_duplicates()
provider_directory = provider_directory[~provider_directory['CCN'].duplicated(keep='first')]
provider_directory.head(10)
output_final = pd.merge(left = output, right = provider_directory, how = "left", on = 'CCN' )
output_final.to_csv("test.csv")

C:\Users\email\AppData\Local\Temp\ipykernel_13792\1796689882.py:2: DtypeWarning: Columns (16,59) have mixed types. Specify dtype option on import or set low_memory=False.
  provider_directory_2 = pd.read_csv(r"C:\Users\email\OneDrive\Documents\Python\zip_codes\CMS_directory_every_provider.csv")
C:\Users\email\AppData\Local\Temp\ipykernel_13792\1796689882.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  provider_directory = provider_directory_1.append(other = provider_directory_2).drop(columns = ['Unnamed: 0'])

In [143]:
print(len(provider_directory["CCN"]))
print(len(provider_directory["CCN"].unique()))
print(output.shape)
print(output_final.shape)
print(output_final.drop_duplicates().shape)

24542
24542
(27540, 30)
(27540, 90)
(27540, 90)

In [137]:
provider_directory["CCN"][provider_directory["CCN"].duplicated()]
provider_directory["CCN"].duplicated()

'provider_directory["CCN"].duplicated' is not recognized as an internal or external command,
operable program or batch file.

In [135]:
output_final.loc[output_final['CCN'] == '245616']

,ProviderID,CCN,Type_Of_Facility,Medicare_Certified_Beds,Total_Staffed_Beds,ZipCode,KeepState,FINAL_Zip_First_3,FINAL_RUCA1,Hospital_Overall_rating,...,Hospital_readmission_reduction_adjustment,Model_1_bundle_percent,Hospital_acquired_condition_(HAC)_reduction_program_participant,Uncompensated_care_amount,Electronic_health_record_(EHR)_incentive_program_reduction_indicator,Low-volume_adjustment_factor,County_code,State_code,Medicare_performance_adjustment,LTCH_DPP_indicator
13326,704931,245616,Medicare and Medicaid,40.0,NaN,56751,MN,567,7,NaN,...,0.0,0.0,N,$0.00,NaN,0.0,27135.0,24,0.0,NaN
13327,704931,245616,Medicare and Medicaid,40.0,NaN,56751,MN,567,7,NaN,...,0.0,0.0,N,$0.00,NaN,0.0,27135.0,24.0,0.0,NaN

In [140]:
output_fixed_1 = output_final[ ~ output_final["CCN"].duplicated(keep='first')]

In [147]:
df_1 = pd.read_csv("test.csv", dtype="string")
df_2 = pd.read_csv("final_result.csv", dtype ='string')
df_1.equals(df_2)

False